<?xml version="1.0" encoding="UTF-8"?>
<!--
  Instructions: Add new document types to the end of this document
  
  (see hub document XML comments for instructions)
-->
<!DOCTYPE schemadocs [
	<!ELEMENT schemadocs (schema+)>
	<!ELEMENT schema (name, description, processes, submitterRole, receiverRole, examples)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT description (#PCDATA | link)*>
	<!ELEMENT process (#PCDATA)>
	<!ELEMENT link (#PCDATA)>
	<!ATTLIST link
		schema CDATA #IMPLIED
	>
	<!ATTLIST link
		figure CDATA #IMPLIED
	>
	<!ELEMENT example (#PCDATA)>
	<!ELEMENT submitterRole (#PCDATA)>
	<!ELEMENT receiverRole (#PCDATA)>
	<!ELEMENT processes (process*)>
	<!ELEMENT examples (example*)>
]>
<schemadocs>
   <schema>
      <name>Application Response</name>
      <description>A document to indicate the application's response to a transaction. This may be a business response initiated by a user or a technical response sent automatically by an application.</description>
      <processes/>
      <submitterRole>Sender</submitterRole>
      <receiverRole>Receiver</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Attached Document</name>
      <description>A wrapper that allows a document of any kind to be packaged with the UBL document that references it.</description>
      <processes/>
      <submitterRole>Sender</submitterRole>
      <receiverRole>Receiver</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Awarded Notification</name>
      <description>The document used to communicate a contract award to the winner.</description>
      <processes>
         <process>Pre-award</process>
      </processes>
      <submitterRole>Contracting Authority</submitterRole>
      <receiverRole>Tenderer</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Bill Of Lading</name>
      <description>A document issued by the party who acts as an agent for a transportation carrier or other agents to the party who gives instructions for the transportation services (shipper, consignor, etc.) stating the details of the transportation, charges, and terms and conditions under which the transportation service is provided. The party issuing this document does not necessarily provide the physical transportation service. The information in the Bill of Lading corresponds to the information on the Forwarding Instructions. It is used for any mode of transport. A Bill of Lading can serve as a contractual document between the parties for the transportation service. The document evidences a contract of carriage by sea and the acceptance of responsibility for the goods by the carrier, by which the carrier undertakes to deliver the goods against surrender of the document. A provision in the document that the goods are to be delivered to the order of a named person, or to order, or to bearer, constitutes such an undertaking.</description>
      <processes>
         <process>Transport</process>
      </processes>
      <submitterRole>Freight Forwarder, Carrier</submitterRole>
      <receiverRole>Consignor (or Consignee), Freight Forwarder</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Call For Tenders</name>
      <description>A document used by a Contracting Party to define a procurement project to buy goods, services, or works during a specified period.</description>
      <processes>
         <process>Pre-award</process>
      </processes>
      <submitterRole>Contracting Authority</submitterRole>
      <receiverRole>Tenderer</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Catalogue</name>
      <description>A document that describes items, prices, and price validity.</description>
      <processes>
         <process>Catalogue</process>
         <process>Create Catalogue</process>
         <process>Delete Catalogue</process>
         <process>Update Catalogue Item Specification</process>
         <process>Update Catalogue Pricing</process>
         <process>Initial Stocking of the Area by Producer</process>
         <process>Permanent Replenishment</process>
         <process>Price Adjustments</process>
         <process>Transfer of Base Item Catalogue</process>
         <process>Changes to the Item Catalogue</process>
         <process>Changes to the Article Catalogue</process>
      </processes>
      <submitterRole>Seller</submitterRole>
      <receiverRole>Contracting Party</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Catalogue Deletion</name>
      <description>A document used to cancel an entire Catalogue.</description>
      <processes>
         <process>Catalogue</process>
      </processes>
      <submitterRole>Seller</submitterRole>
      <receiverRole>Contracting Party</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Catalogue Item Specification Update</name>
      <description>A document used to update information (e.g., technical descriptions and properties) about Items in an existing Catalogue.</description>
      <processes>
         <process>Catalogue</process>
      </processes>
      <submitterRole>Seller</submitterRole>
      <receiverRole>Contracting Party</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Catalogue Pricing Update</name>
      <description>A document used to update information about prices in an existing Catalogue.</description>
      <processes>
         <process>Catalogue</process>
      </processes>
      <submitterRole>Seller</submitterRole>
      <receiverRole>Contracting Party</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Catalogue Request</name>
      <description>A document used to request a Catalogue.</description>
      <processes>
         <process>Catalogue</process>
      </processes>
      <submitterRole>Contracting Party</submitterRole>
      <receiverRole>Seller</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Certificate Of Origin</name>
      <description>A document that describes the Certificate of Origin.</description>
      <processes>
         <process>Certification of Origin of Goods</process>
      </processes>
      <submitterRole>Exporter, Issuer</submitterRole>
      <receiverRole>Issuer, Importer</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Contract Award Notice</name>
      <description>A document published by a Contracting Party to announce the awarding of a procurement project.</description>
      <processes>
         <process>Pre-award</process>
      </processes>
      <submitterRole>Contracting Authority</submitterRole>
      <receiverRole>Tenderer</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Contract Notice</name>
      <description>A document used by a Contracting party to announce a project to buy goods, services, or works.</description>
      <processes>
         <process>Pre-award</process>
      </processes>
      <submitterRole>Contracting Authority</submitterRole>
      <receiverRole>Tenderer</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Credit Note</name>
      <description>A document used to specify credits due to the Debtor from the Creditor.</description>
      <processes>
         <process>Billing</process>
      </processes>
      <submitterRole>Supplier Accounting Party</submitterRole>
      <receiverRole>Customer Accounting Party</receiverRole>
      <examples>
         <example>UBL-CreditNote-2.0-Example.xml</example>
         <example>UBL-CreditNote-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Debit Note</name>
      <description>A document used to specify debts incurred by the Debtor.</description>
      <processes>
         <process>Billing</process>
      </processes>
      <submitterRole>Customer Accounting Party</submitterRole>
      <receiverRole>Supplier Accounting Party</receiverRole>
      <examples>
         <example>UBL-DebitNote-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Despatch Advice</name>
      <description>A document used to describe the despatch or delivery of goods and services.</description>
      <processes>
         <process>Logistics</process>
      </processes>
      <submitterRole>Despatch</submitterRole>
      <receiverRole>Delivery</receiverRole>
      <examples>
         <example>UBL-DespatchAdvice-2.0-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Document Status</name>
      <description>A document used to provide information about the status of a collaboration/process associated with a document.</description>
      <processes/>
      <submitterRole>Party currently controlling Status of the collaboration</submitterRole>
      <receiverRole>Party requesting Status on collaboration</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Document Status Request</name>
      <description>A document used to request the status of a collaboration/process associated with a document.</description>
      <processes/>
      <submitterRole>Party requesting Status on collaboration</submitterRole>
      <receiverRole>Party currently controlling Status of the collaboration</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Exception Criteria</name>
      <description>A document used to specify the thresholds for forecast variance, product activity, and performance history beyond which exceptions will be triggered.</description>
      <processes>
         <process>Collaborative Planning, Forecasting, and Replenishment</process>
      </processes>
      <submitterRole>Buyer, Seller</submitterRole>
      <receiverRole>Buyer, Seller</receiverRole>
      <examples>
         <example>UBL-ExceptionCriteria-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Exception Notification</name>
      <description>A document used to notify an exception in forecast variance, product activity, or performance history.</description>
      <processes>
         <process>Collaborative Planning, Forecasting, and Replenishment</process>
      </processes>
      <submitterRole>Buyer, Seller</submitterRole>
      <receiverRole>Buyer, Seller</receiverRole>
      <examples>
         <example>UBL-ExceptionNotification-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Forecast</name>
      <description>A document used to forecast sales or orders.</description>
      <processes>
         <process>Collaborative Planning, Forecasting, and Replenishment</process>
      </processes>
      <submitterRole>Buyer, Seller</submitterRole>
      <receiverRole>Buyer, Seller</receiverRole>
      <examples>
         <example>UBL-Forecast-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Forecast Revision</name>
      <description>A document used to revise a Forecast.</description>
      <processes>
         <process>Collaborative Planning, Forecasting, and Replenishment</process>
      </processes>
      <submitterRole>Buyer, Seller</submitterRole>
      <receiverRole>Buyer, Seller</receiverRole>
      <examples>
         <example>UBL-ForecastRevision-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Forwarding Instructions</name>
      <description>A document issued to a forwarder, giving instructions regarding the action to be taken for the forwarding of goods described therein. Forwarding Instructions is used by any party who gives instructions for the transportation services required for a consignment of goods to any party who is contracted to provide the transportation services. The parties who issue this document are commonly referred to as the shipper or consignor, while the parties who receive this document are forwarders, carriers, shipping agents, etc. This document may also be issued by a forwarder or shipping agent in its capacity as a shipper. This document can be used to arrange for the transportation (1) of different types of goods or cargoes; (2) whether containerized or non-containerized; (3) through different modes of transport including multi-modal; and (4) from any origin to any destination.</description>
      <processes>
         <process>Transport</process>
      </processes>
      <submitterRole>Consignor (or Consignee), Freight Forwarder</submitterRole>
      <receiverRole>Freight Forwarder, Carrier</receiverRole>
      <examples>
         <example>UBL-ForwardingInstructions-2.0-Example-International.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Freight Invoice</name>
      <description>A document stating the charges incurred for a logistics service.</description>
      <processes>
         <process>Freight Billing</process>
      </processes>
      <submitterRole>Freight Forwarder</submitterRole>
      <receiverRole>Consignor or Consignee</receiverRole>
      <examples>
         <example>UBL-FreightInvoice-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Fulfilment Cancellation</name>
      <description>A document used to cancel an entire fulfilment document (Despatch Advice or Receipt Advice).</description>
      <processes>
         <process>Logistics</process>
      </processes>
      <submitterRole>Buyer or Seller</submitterRole>
      <receiverRole>Seller or Buyer</receiverRole>
      <examples>
         <example>UBL-FulfilmentCancellation-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Goods Item Itinerary</name>
      <description>A document providing details relating to a transport service, such as transport movement, identification of equipment and goods, subcontracted service providers, etc.</description>
      <processes>
         <process>Intermodal Freight Management</process>
      </processes>
      <submitterRole>Transport Service Provider</submitterRole>
      <receiverRole>Transport User</receiverRole>
      <examples>
         <example>UBL-GoodsItemItinerary-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Guarantee Certificate</name>
      <description>A document to notify the deposit of a bid bond guarantee.</description>
      <processes>
         <process>Pre-award</process>
      </processes>
      <submitterRole>Tenderer</submitterRole>
      <receiverRole>Contracting Authority</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Instruction For Returns</name>
      <description>A document used to initiate a return of goods. The producer is requesting the return of products that are not selling well, either to use in other places or to free up rack or shelf space.</description>
      <processes>
         <process>Cyclic Replenishment Program (CRP)</process>
      </processes>
      <submitterRole>Seller</submitterRole>
      <receiverRole>Buyer</receiverRole>
      <examples>
         <example>UBL-InstructionForReturns-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Inventory Report</name>
      <description>A report on the quantities of each item that are, or will be, in stock. This document is sent by a Buyer (for example a retailer) to a Seller (for example a producer).</description>
      <processes>
         <process>Cyclic Replenishment Program (CRP)</process>
      </processes>
      <submitterRole>Buyer</submitterRole>
      <receiverRole>Seller</receiverRole>
      <examples>
         <example>UBL-InventoryReport-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Invoice</name>
      <description>A document used to request payment.</description>
      <processes>
         <process>Billing</process>
      </processes>
      <submitterRole>Supplier Accounting Party</submitterRole>
      <receiverRole>Customer Accounting Party</receiverRole>
      <examples>
         <example>UBL-Invoice-2.0-Example.xml</example>
         <example>UBL-Invoice-2.1-Example.xml</example>
         <example>UBL-Invoice-2.1-Example-Trivial.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Item Information Request</name>
      <description>A document used to request product activity, forecast, or performance data.</description>
      <processes>
         <process>Collaborative Planning, Forecasting, and Replenishment</process>
      </processes>
      <submitterRole>Buyer, Seller</submitterRole>
      <receiverRole>Buyer, Seller</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Order</name>
      <description>A document used to order goods and services.</description>
      <processes>
         <process>Ordering (post-award)</process>
      </processes>
      <submitterRole>Buyer</submitterRole>
      <receiverRole>Seller</receiverRole>
      <examples>
         <example>UBL-Order-2.0-Example.xml</example>
         <example>UBL-Order-2.1-Example.xml</example>
         <example>UBL-Order-2.0-Example-International.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Order Cancellation</name>
      <description>A document used to cancel an entire Order.</description>
      <processes>
         <process>Ordering (post-award)</process>
         <process>Logistics</process>
      </processes>
      <submitterRole>Buyer</submitterRole>
      <receiverRole>Seller</receiverRole>
      <examples>
         <example>UBL-OrderCancellation-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Order Change</name>
      <description>A document used to specify changes to an existing Order.</description>
      <processes>
         <process>Ordering (post-award)</process>
         <process>Logistics</process>
      </processes>
      <submitterRole>Buyer</submitterRole>
      <receiverRole>Seller</receiverRole>
      <examples>
         <example>UBL-OrderChange-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Order Response</name>
      <description>A document used to indicate detailed acceptance or rejection of an Order or to make a counter-offer.</description>
      <processes>
         <process>Ordering (post-award)</process>
      </processes>
      <submitterRole>Seller</submitterRole>
      <receiverRole>Buyer</receiverRole>
      <examples>
         <example>UBL-OrderResponse-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Order Response Simple</name>
      <description>A document used to indicate simple acceptance or rejection of an entire Order.</description>
      <processes>
         <process>Ordering (post-award)</process>
      </processes>
      <submitterRole>Seller</submitterRole>
      <receiverRole>Buyer</receiverRole>
      <examples>
         <example>UBL-OrderResponseSimple-2.0-Example.xml</example>
         <example>UBL-OrderResponseSimple-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Packing List</name>
      <description>A document describing how goods are packed.</description>
      <processes>
         <process>Transport</process>
      </processes>
      <submitterRole>Consignor</submitterRole>
      <receiverRole>Freight Forwarder</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Prior Information Notice</name>
      <description>A document used by a contracting party to declare the intention to buy goods, services, or works during a specified period.</description>
      <processes>
         <process>Pre-award</process>
      </processes>
      <submitterRole>Contracting Authority</submitterRole>
      <receiverRole>Tenderer</receiverRole>
      <examples>
         <example>UBL-PriorInformationNotice-2.2-Example-Embedded.xml</example>
         <example>UBL-PriorInformationNotice-2.2-Example-External.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Product Activity</name>
      <description>A document reporting the movement of goods at specified retail locations for inventory tracking purposes.</description>
      <processes>
         <process>Collaborative Planning, Forecasting, and Replenishment</process>
         <process>Vendor Managed Inventory</process>
      </processes>
      <submitterRole>Buyer</submitterRole>
      <receiverRole>Seller</receiverRole>
      <examples>
         <example>UBL-ProductActivity-2.1-Example-1.xml</example>
         <example>UBL-ProductActivity-2.1-Example-2.xml</example>
         <example>UBL-ProductActivity-2.1-Example-3.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Quotation</name>
      <description>A document used to quote for the provision of goods and services.</description>
      <processes>
         <process>Quotation</process>
      </processes>
      <submitterRole>Seller</submitterRole>
      <receiverRole>Originator</receiverRole>
      <examples>
         <example>UBL-Quotation-2.0-Example.xml</example>
         <example>UBL-Quotation-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Receipt Advice</name>
      <description>A document used to describe the receipt of goods and services.</description>
      <processes>
         <process>Logistics</process>
      </processes>
      <submitterRole>Delivery</submitterRole>
      <receiverRole>Despatch</receiverRole>
      <examples>
         <example>UBL-ReceiptAdvice-2.0-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Reminder</name>
      <description>A document used to remind a customer of payments past due.</description>
      <processes>
         <process>Billing</process>
      </processes>
      <submitterRole>Supplier Accounting Party and/or Payee</submitterRole>
      <receiverRole>Customer Accounting Party and/or Payee</receiverRole>
      <examples>
         <example>UBL-Reminder-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Remittance Advice</name>
      <description>A document that specifies details of an actual payment.</description>
      <processes>
         <process>Payment Notification</process>
      </processes>
      <submitterRole>Supplier Accounting Party and/or Payee</submitterRole>
      <receiverRole>Customer Accounting Party and/or Payee</receiverRole>
      <examples>
         <example>UBL-RemittanceAdvice-2.0-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Request For Quotation</name>
      <description>A document used to request a Quotation for goods and services from a Seller.</description>
      <processes>
         <process>Quotation</process>
      </processes>
      <submitterRole>Originator</submitterRole>
      <receiverRole>Seller</receiverRole>
      <examples>
         <example>UBL-RequestForQuotation-2.0-Example.xml</example>
         <example>UBL-RequestForQuotation-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Retail Event</name>
      <description>A document used to specify basic information about retail events (such as promotions, product introductions, and community or environmental events) that affect supply or demand.</description>
      <processes>
         <process>Cyclic Replenishment Program (CRP)</process>
      </processes>
      <submitterRole>Buyer, Seller</submitterRole>
      <receiverRole>Buyer, Seller</receiverRole>
      <examples>
         <example>UBL-RetailEvent-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Self Billed Credit Note</name>
      <description>A credit note created by the debtor in a self billing arrangement with a creditor; Self Billed Credit Note replaces Debit Note in such arrangements.</description>
      <processes>
         <process>Billing</process>
      </processes>
      <submitterRole>Customer Accounting Party</submitterRole>
      <receiverRole>Supplier Accounting Party</receiverRole>
      <examples>
         <example>UBL-SelfBilledCreditNote-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Self Billed Invoice</name>
      <description>An Invoice document created by the Customer (rather than the Supplier) in a Self Billing relationship.</description>
      <processes>
         <process>Billing</process>
      </processes>
      <submitterRole>Customer Accounting Party</submitterRole>
      <receiverRole>Supplier Accounting Party</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Statement</name>
      <description>A document used to report the status of orders, billing, and payment. This document is a statement of account, not a summary invoice.</description>
      <processes>
         <process>Billing</process>
      </processes>
      <submitterRole>Supplier Accounting Party</submitterRole>
      <receiverRole>Customer Accounting Party</receiverRole>
      <examples>
         <example>UBL-Statement-2.0-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Stock Availability Report</name>
      <description>A report on the quantities of each item that are, or will be, in stock. This document is sent by a Seller (for example a producer) to a Buyer (for example a retailer).</description>
      <processes>
         <process>Cyclic Replenishment Program (CRP)</process>
      </processes>
      <submitterRole>Seller (Producer)</submitterRole>
      <receiverRole>Buyer (Retailer)</receiverRole>
      <examples>
         <example>UBL-StockAvailabilityReport-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Tender</name>
      <description>A document whereby an economic operator (the tenderer) makes a formal offer (the tender) to a contracting authority to execute an order for the supply or purchase of goods, or for the execution of work, according to the terms of a proposed contract.</description>
      <processes>
         <process>Pre-award</process>
      </processes>
      <submitterRole>Tenderer</submitterRole>
      <receiverRole>Contracting Authority</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Tender Receipt</name>
      <description>A document sent by a contracting party to an economic operator acknowledging receipt of a Tender.</description>
      <processes>
         <process>Pre-award</process>
      </processes>
      <submitterRole>Contracting Authority</submitterRole>
      <receiverRole>Tenderer</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Tenderer Qualification</name>
      <description>A document declaring the qualifications of a tenderer.</description>
      <processes>
         <process>Pre-award</process>
      </processes>
      <submitterRole>Tenderer</submitterRole>
      <receiverRole>Contracting Authority</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Tenderer Qualification Response</name>
      <description>A document issued by a procurement organization to notify an economic operator whether it has been admitted to or excluded from the tendering process.</description>
      <processes>
         <process>Pre-award</process>
      </processes>
      <submitterRole>Contracting Authority</submitterRole>
      <receiverRole>Tenderer</receiverRole>
      <examples/>
   </schema>
   <schema>
      <name>Trade Item Location Profile</name>
      <description>A document specifying trade item attributes relating to replenishment policies.</description>
      <processes>
         <process>Collaborative Planning, Forecasting, and Replenishment</process>
      </processes>
      <submitterRole>Buyer, Seller</submitterRole>
      <receiverRole>Buyer, Seller</receiverRole>
      <examples>
         <example>UBL-TradeItemLocationProfile-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Transport Execution Plan</name>
      <description>A document used in the negotiation of a transport service between a transport user and a transport service provider.</description>
      <processes>
         <process>Intermodal Freight Management</process>
      </processes>
      <submitterRole>Transport Service Provider, Transport User</submitterRole>
      <receiverRole>Transport User, Transport Service Provider</receiverRole>
      <examples>
         <example>UBL-TransportExecutionPlan-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Transport Execution Plan Request</name>
      <description>A document sent by a transport user to request a transport service from a transport service provider.</description>
      <processes>
         <process>Intermodal Freight Management</process>
      </processes>
      <submitterRole>Transport User</submitterRole>
      <receiverRole>Transport Service Provider</receiverRole>
      <examples>
         <example>UBL-TransportExecutionPlanRequest-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Transport Progress Status</name>
      <description>A document sent from a Transportation Network Manager to a Transport Service Provider giving the status of the whereabouts and schedule of the transport means involved in a transport service.</description>
      <processes>
         <process>Intermodal Freight Management</process>
      </processes>
      <submitterRole>Transportation Network Manager</submitterRole>
      <receiverRole>Transport Service Provider</receiverRole>
      <examples>
         <example>UBL-TransportProgressStatus-2.1-Example.xml</example>
      </examples>
   </schema>
   <schema>
      <name>Transport Progress Status Request</name>
      <description>A document sent from a transport service provider to a transportation network manager requesting a Transport Progress Status.</description>
      <processes>
         <process>Intermodal Freight Management</process>
      </processes>
      <submitterRole>Transport Service Provider</submitterRole>
      <receiverRole>Transportation Network Manager</receiverRole>
      <examples>
         <example>UBL-TransportProgressStatusRequest-2.1-Example.xml</example>